apiVersion: v1 
kind: Service
metadata:
  name: tetris-service-deployment
  label: 
    app: tetris-deployment  
spec:
  selector:
    app: tetris-deployment
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 80
  type: LoadBalancer
